In [ ]:
Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix.

In [1]:
import numpy as np

arr = np.arange(1, 11)
matrix = arr.reshape(2, 5)

print("Original Array:")
print(arr)

print("\n2x5 Matrix:")
print(matrix)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

2x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index.

In [2]:
import numpy as np

arr = np.arange(1, 21)

print("Array:")
print(arr)

print("\nElements between 5th and 15th index:")
print(arr[5:16])

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Elements between 5th and 15th index:
[ 6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above

In [3]:
import numpy as np

arr = np.arange(1, 21)

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))

Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [ ]:
Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting.

In [4]:
import numpy as np

x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

y = np.array([1, 2, 3, 4])

result = x - y

print("2D Array:")
print(x)

print("\n1D Array:")
print(y)

print("\nResult after Broadcasting:")
print(result)

2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

1D Array:
[1 2 3 4]

Result after Broadcasting:
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


In [2]:
import pandas as pd

data = {
    "Name": ["John", "Alice", "David"],
    "Age": [25, 30, 35],
    "Gender": ["Male", "Female", "Male"]
}

df = pd.DataFrame(data)

print("\nOriginal DataFrame:\n", df)

df["Occupation"] = ["Programmer", "Manager", "Analyst"]

print("\nDataFrame with Occupation:\n", df)

filtered_df = df[df["Age"] >= 30]

print("\nFiltered DataFrame (Age >= 30):\n", filtered_df)

df.to_csv("student_data.csv", index=False)

new_df = pd.read_csv("student_data.csv")

print("\nDataFrame read from CSV:\n", new_df)



Original DataFrame:
     Name  Age  Gender
0   John   25    Male
1  Alice   30  Female
2  David   35    Male

DataFrame with Occupation:
     Name  Age  Gender  Occupation
0   John   25    Male  Programmer
1  Alice   30  Female     Manager
2  David   35    Male     Analyst

Filtered DataFrame (Age >= 30):
     Name  Age  Gender Occupation
1  Alice   30  Female    Manager
2  David   35    Male    Analyst

DataFrame read from CSV:
     Name  Age  Gender  Occupation
0   John   25    Male  Programmer
1  Alice   30  Female     Manager
2  David   35    Male     Analyst
